// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_processor.proto
#ifndef GRPC_file_5fprocessor_2eproto__INCLUDED
#define GRPC_file_5fprocessor_2eproto__INCLUDED

#include "file_processor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace file_processor {

class FileProcessorService final {
 public:
  static constexpr char const* service_full_name() {
    return "file_processor.FileProcessorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> CompressPDF(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(CompressPDFRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> AsyncCompressPDF(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(AsyncCompressPDFRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> PrepareAsyncCompressPDF(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(PrepareAsyncCompressPDFRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CompressPDF(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::ProcessedFileChunk>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* CompressPDFRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* AsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* PrepareAsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> CompressPDF(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(CompressPDFRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> AsyncCompressPDF(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(AsyncCompressPDFRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>> PrepareAsyncCompressPDF(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>>(PrepareAsyncCompressPDFRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CompressPDF(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::ProcessedFileChunk>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* CompressPDFRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* AsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* PrepareAsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CompressPDF_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CompressPDF(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_CompressPDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CompressPDF() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CompressPDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompressPDF(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompressPDF(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CompressPDF<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CompressPDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CompressPDF() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->CompressPDF(context); }));
    }
    ~WithCallbackMethod_CompressPDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompressPDF(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* CompressPDF(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_CompressPDF<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CompressPDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CompressPDF() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CompressPDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompressPDF(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CompressPDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CompressPDF() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CompressPDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompressPDF(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompressPDF(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CompressPDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CompressPDF() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->CompressPDF(context); }));
    }
    ~WithRawCallbackMethod_CompressPDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompressPDF(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* CompressPDF(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace file_processor


#endif  // GRPC_file_5fprocessor_2eproto__INCLUDED
