// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_processor.proto

#include "file_processor.pb.h"
#include "file_processor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace file_processor {

static const char* FileProcessorService_method_names[] = {
  "/file_processor.FileProcessorService/CompressPDF",
};

std::unique_ptr< FileProcessorService::Stub> FileProcessorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileProcessorService::Stub> stub(new FileProcessorService::Stub(channel, options));
  return stub;
}

FileProcessorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CompressPDF_(FileProcessorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* FileProcessorService::Stub::CompressPDFRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>::Create(channel_.get(), rpcmethod_CompressPDF_, context);
}

void FileProcessorService::Stub::async::CompressPDF(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::file_processor::FileChunk,::file_processor::ProcessedFileChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::file_processor::FileChunk,::file_processor::ProcessedFileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_CompressPDF_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* FileProcessorService::Stub::AsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>::Create(channel_.get(), cq, rpcmethod_CompressPDF_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>* FileProcessorService::Stub::PrepareAsyncCompressPDFRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>::Create(channel_.get(), cq, rpcmethod_CompressPDF_, context, false, nullptr);
}

FileProcessorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileProcessorService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< FileProcessorService::Service, ::file_processor::FileChunk, ::file_processor::ProcessedFileChunk>(
          [](FileProcessorService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::file_processor::ProcessedFileChunk,
             ::file_processor::FileChunk>* stream) {
               return service->CompressPDF(ctx, stream);
             }, this)));
}

FileProcessorService::Service::~Service() {
}

::grpc::Status FileProcessorService::Service::CompressPDF(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::file_processor::ProcessedFileChunk, ::file_processor::FileChunk>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace file_processor

